services:
  - type: web
    name: first-city-credit-union
    runtime: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/ping
    autoDeploy: false
