services:
  - type: web
    name: fusion-starter
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /api/ping
    disks:
      - name: data
        mountPath: /mnt/data
        sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /mnt/data/auth.db
      - key: FRONTEND_URL
        fromService:
          type: web
          name: fusion-starter
          property: url
      - key: PORT
        fromService:
          type: web
          name: fusion-starter
          property: port
    autoDeploy: true
